#!/usr/bin/env escript
-include_lib("xmerl/include/xmerl.hrl").

get_cookie() ->
    {Xml, _} = xmerl_scan:file("/etc/cloudbuilder.conf"),
    [#xmlText{value=Cookie}] = xmerl_xpath:string("//cookie/text()", Xml),
    Cookie.

main(Params) ->
    net_kernel:start([shell]),

    io:format("Params: ~p~n", [Params]),

    F = fun(Param) ->
		case string:tokens(Param, "=") of
		    [Lhs, Rhs] -> {Lhs, Rhs};
		    Token -> throw({bad_token, Token})
		end
	end,
    PL = [F(Param) || Param <- Params],

    Cookie = case proplists:lookup("cookie", PL) of
		 {_, C} -> C;
		 _ -> get_cookie()
	     end,
    erlang:set_cookie(node(), list_to_atom(Cookie)),
    
    Host = case proplists:lookup("host", PL) of
	       {_, H} -> H;
	       _ -> net_adm:localhost()
	   end,
    Target = list_to_atom( "cloudbuilderd@" ++ Host),

    io:format("Connecting to ~p with cookie ~s~n", [Target, Cookie]),

    true = net_kernel:connect_node(Target),
    
    shell:start(),
    
    loop().

loop() ->
    timer:sleep(10000000),
    loop().



